// <auto-generated />
using System;
using EntityFrameWorkLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFrameWorkLib.Migrations
{
    [DbContext(typeof(LolContext))]
    [Migration("20230314230906_MyMigration")]
    partial class MyMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("EntityFrameWorkLib.ChampionEntity", b =>
                {
                    b.Property<int>("UniqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Class")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UniqueId");

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("EntityFrameWorkLib.LargeImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Base64")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("championId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("championId")
                        .IsUnique();

                    b.ToTable("LargeImage");
                });

            modelBuilder.Entity("EntityFrameWorkLib.SkillEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkillType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("EntityFrameWorkLib.LargeImageEntity", b =>
                {
                    b.HasOne("EntityFrameWorkLib.ChampionEntity", "champion")
                        .WithOne("LargeImageEntity")
                        .HasForeignKey("EntityFrameWorkLib.LargeImageEntity", "championId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("champion");
                });

            modelBuilder.Entity("EntityFrameWorkLib.ChampionEntity", b =>
                {
                    b.Navigation("LargeImageEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
