kind: pipeline
type: docker
name: EfCore_Lol_S4

trigger:
  event:
    - push

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - dotnet restore LeagueOfLegends.sln
      - dotnet build LeagueOfLegends.sln -c Release --no-restore
      - dotnet publish LeagueOfLegends.sln -c Release --no-restore -o CI_PROJECT_DIR/build/release

  - name: tests
    image: mcr.microsoft.com/dotnet/sdk:7.0
    commands:
      - dotnet restore LeagueOfLegends.sln
      - dotnet test LeagueOfLegends.sln --no-restore
    depends_on: [build]

  - name: code-analysis
    image: pubhub.codefirst.iut.uca.fr/thbellem/codefirst-dronesonarplugin-dotnet7
    commands:
      - cd Solution1/
      - dotnet restore LeagueOfLegends.sln
      - dotnet sonarscanner begin /k:EfCore_Lol_S4 /d:sonar.host.url="https://codefirst.iut.uca.fr/sonar"  /d:sonar.coverageReportPaths="coveragereport/SonarQube.xml" /d:sonar.login=$${PLUGIN_SONAR_TOKEN}
      - dotnet build LeagueOfLegends.sln -c Release --no-restore
      - dotnet test LeagueOfLegends.sln --logger trx --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura --collect "XPlat Code Coverage"
      - reportgenerator -reports:"**/coverage.cobertura.xml" -reporttypes:SonarQube -targetdir:"coveragereport"
      - dotnet publish LeagueOfLegends.sln -c Release --no-restore -o $CI_PROJECT_DIR/build/release
      - dotnet sonarscanner end /d:sonar.login=$${PLUGIN_SONAR_TOKEN}
    secrets: [ SECRET_SONAR_LOGIN ]
    settings:
    # accessible en ligne de commande par $${PLUGIN SONAR HOST}
      sonar_host: https://codefirst.ddns.net/sonar/
# accessible en ligne de commande par $${PLUGIN_SONAR_TOKEN}
      sonar_token:
        from_secret: SECRET_SONAR_LOGIN
      depends on: [tests]

  - name: generate-and-deploy-docs
    image: pubhub.codefirst.iut.uca.fr/thbellem/codefirst-docdeployer
    volumes:
      - name: docs
        path: /Document
    commands:
      - cd Document/doxygen
      - doxygen Doxyfile
      - /entrypoint.sh
    when:
      branch:
        - master
    depends_on: [ build ]
volumes:
- name: docs
  temp: {}